[env:lilygo-t-sim7670g-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags = 
    -D CORE_DEBUG_LEVEL=3
    -D BOARD_HAS_PSRAM
    -D TINY_GSM_MODEM_SIM7600
    -D TINY_GSM_RX_BUFFER=1024
    -D ARDUINO_USB_CDC_ON_BOOT=1  ; Directs Serial output to native USB CDC
    -D ARDUINO_USB_MODE=1

monitor_dtr = 1
monitor_rts = 1

lib_deps = 
    vshymanskyy/TinyGSM @ ^0.11.7
    vshymanskyy/StreamDebugger @ ^1.0.1
    ; adafruit/Adafruit BME680 Library
    ; adafruit/Adafruit Unified Sensor